# Generated by Django 5.0.6 on 2024-06-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image_post_link_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flips', models.IntegerField(choices=[(0, 'Keep'), (1, 'Flip')])),
                ('piles', models.IntegerField(choices=[(0, 'Pile 1'), (1, 'Pile 2')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
